#spring:
#  profiles:
#    active: mysql
#
#  batch:
#    job:
#      names: ${job.name:NONE}
#logging.level.org.springframework.batch: DEBUG
#---
#spring:
#  profiles: mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: finutflab
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: mysql
